// <auto-generated />
namespace ATEVersions_Management.Migrations.DevSide
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removeIdxVersionName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeIdxVersionName));
        
        string IMigrationMetadata.Id
        {
            get { return "202311140750057_removeIdxVersionName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
