// <auto-generated />
namespace ATEVersions_Management.Migrations.DevSide
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createGRR_TABLE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createGRR_TABLE));
        
        string IMigrationMetadata.Id
        {
            get { return "202401111212261_createGRR_TABLE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
