// <auto-generated />
namespace ATEVersions_Management.Migrations.DevSide
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class extendCapacityModifyNoteOfTEST_PLAN_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(extendCapacityModifyNoteOfTEST_PLAN_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202401060728079_extendCapacityModifyNoteOfTEST_PLAN_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
