-- ========= COPYIC_TABLE =========
SELECT * FROM COPYIC_TABLE
GO
ALTER TABLE COPYIC_TABLE
ADD MO NVARCHAR(20) NULL,	
	MPN NVARCHAR(20) NULL,
	DOT_COLOR1 NVARCHAR(20) NULL,
	DOT_COLOR2 NVARCHAR(20) NULL,
	DOT_COLOR3 NVARCHAR(20) NULL,
	IC_IMAGES VARBINARY(MAX) NULL