GO -- ========= #REGION::ATE VERSION STRUCTURES ALTER =========
SELECT * FROM USERS WHERE UserName LIKE 'V1060524'
UPDATE USERS SET Department = 'TE'

GO -- ========= #ENDREGION::ATE VERSION STRUCTURES ALTER =========
GO -- ========= #REGION::MESSAGE SYSTEM DATA TABLES =========
CREATE TABLE MESSAGE_GROUP(
	GROUP_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	GROUP_NAME NVARCHAR(200) NOT NULL UNIQUE,
	CREATE_BY INT NULL,
	CREATE_DATE DATETIME NULL,
	IS_ACTIVE BIT NULL
)
CREATE TABLE MESSAGE_USER_GROUP(
	USER_GROUP_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[USER_ID] INT NOT NULL,
	GROUP_ID INT NOT NULL,
	ROLE_IN_GROUP NVARCHAR(30) NULL,
	CREATE_DATE DATETIME NULL,
	IS_ACTIVE BIT NULL,
    CONSTRAINT [FK_dbo.MESSAGE_USER_GROUP_dbo.USER_USER_ID] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[USERS] ([UserID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dbo.MESSAGE_USER_GROUP_dbo.MESSAGE_GROUP_GROUP_ID] FOREIGN KEY ([GROUP_ID]) REFERENCES [dbo].[MESSAGE_GROUP] ([GROUP_ID]) ON DELETE CASCADE
)
CREATE TABLE MESSAGE_SENDER(
	MESSAGE_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MESSAGE_PARENT_ID INT NULL,
	SENDER_ID INT NOT NULL,
	MESSAGE_TYPE NVARCHAR(100) NULL,
	MESSAGE_CONTENT NVARCHAR(MAX) NULL,
	DEVICE_NAME_IP NVARCHAR(100) NULL,
	SEND_DATE DATETIME NULL,
	--RECIPIENT_ID INT NULL,
	--RECIPIENT_GROUP_ID INT NULL,
	--RECEIVE_DATE DATETIME NULL
    CONSTRAINT [FK_dbo.MESSAGE_SENDER_dbo.USER_USER_ID] FOREIGN KEY ([SENDER_ID]) REFERENCES [dbo].[USERs] ([USERID]) ON DELETE CASCADE
)
CREATE TABLE MESSAGE_RECIPIENT(
	RECEIVE_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MESSAGE_ID INT NOT NULL,
	RECIPIENT_ID INT NULL,
	RECIPIENT_GROUP_ID INT NULL,
	RECEIVE_DATE DATETIME NULL
	CONSTRAINT [FK_dbo.MESSAGE_RECIPIENT_dbo.MESSAGE_SENDER_MESSAGE_ID] FOREIGN KEY ([MESSAGE_ID]) REFERENCES [dbo].[MESSAGE_SENDER] ([MESSAGE_ID]) ON DELETE CASCADE,	
)
GO -- ========= #ENDREGION::MESSAGE SYSTEM DATA TABLES =========