// <auto-generated />
namespace ATEVersions_Management.Migrations.PublishSide
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alterPROGRAM_TESTPLAN_add2cols : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterPROGRAM_TESTPLAN_add2cols));
        
        string IMigrationMetadata.Id
        {
            get { return "202411190909105_alterPROGRAM_TESTPLAN_add2cols"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
