// <auto-generated />
namespace ATEVersions_Management.Migrations.PublishSide
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alterUSERS_AddDeptCol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterUSERS_AddDeptCol));
        
        string IMigrationMetadata.Id
        {
            get { return "202412020313191_alterUSERS_AddDeptCol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
