// <auto-generated />
namespace ATEVersions_Management.Migrations.ProductionDB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_FATPTable_OPMonitorCols : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_FATPTable_OPMonitorCols));
        
        string IMigrationMetadata.Id
        {
            get { return "202406211204367_add_FATPTable_OPMonitorCols"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
