// <auto-generated />
namespace ATEVersions_Management.Migrations.ProductionDB
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FATP_AddCol_FAIL_NUM_BUFFER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FATP_AddCol_FAIL_NUM_BUFFER));
        
        string IMigrationMetadata.Id
        {
            get { return "202405170226493_FATP_AddCol_FAIL_NUM_BUFFER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
